### ISSUE TITLE
Build on NextJs not working

### ISSUE THREAD

**Issue by lisabeyy** [web3sp/venom-connect#23]
Hey,

I am having issue using this library when i try to build my code with nextJS, it returns the following error: ".next/server/chunks/nekoton_wasm_bg.wasm'"

Any idea, how to work with Nekoton and NextJS ?

**Comment by rightjelkin** [comment]
Hello, yes we know about problems with nekoton and next, but nekoton is not a part of that repository and project at all. You may address issue to [standalone-client](https://github.com/broxus/everscale-standalone-client) repo. If you will receive an answer from authors, kindly please put a link for the answer here

**Comment by alexnguyennz** [comment]
If you're using Next.js 13 and the app router, you'll need to dynamically import the library. E.g.

```ts
const init = async () => {
    const { initVenomConnect } = await import("@/lib/venom"); // where your initVenomConnect code is, in this case lib/venom.ts
    const venomConnect = await initVenomConnect();
    setVenomConnect(venomConnect);
  };
```
I didn't need to do this for pages router.

**Comment by Loque18** [comment]
Hello, @lisabeyy 
I am also working with this library, I found a workaround, please check [this issue](https://github.com/broxus/everscale-standalone-client/issues/11) on everscale-standalone-client repo

**Comment by rightjelkin** [comment]
> Hello, @lisabeyy I am also working with this library, I found a workaround, please check [this issue](https://github.com/broxus/everscale-standalone-client/issues/11) on everscale-standalone-client repo

Might be a solution

**Comment by Loque18** [comment]
> > Hello, @lisabeyy I am also working with this library, I found a workaround, please check [this issue](https://github.com/broxus/everscale-standalone-client/issues/11) on everscale-standalone-client repo
> 
> Might be a solution

I don't think it's a solution, it is instead just a workaround, but ir works, howwever everscale-stand-alone package's mantainers should look for a solution, tho it is more related to nextJS and how it handles wasm files, but it should at least be mentioned on the documentation, so that other devs, don't waste time trying to find a solution.

**Comment by rightjelkin** [comment]
> > > Hello, @lisabeyy I am also working with this library, I found a workaround, please check [this issue](https://github.com/broxus/everscale-standalone-client/issues/11) on everscale-standalone-client repo
> > 
> > 
> > Might be a solution
> 
> I don't think it's a solution, it is instead just a workaround, but ir works, howwever everscale-stand-alone package's mantainers should look for a solution, tho it is more related to nextJS and how it handles wasm files, but it should at least be mentioned on the documentation, so that other devs, don't waste time trying to find a solution.

Anyway, the problem is not about venom-connect, but about provider. Maintainer of provider has answered about including all wasm files in build...I think it will be better and more effective to work with this problem in the issues of provider repo...same for docs - it would be better to have such information there and to have a links

**Comment by rightjelkin** [comment]
> 

Actually you could create a PR for README with your workaround....it would be good for community...at least developers could use it for now.

>
